kafka-cluster:
  priorityClassName: thingpark-enterprise-data
  kafka:
    resources:
      limits:
        memory: 700Mi
  zookeeper:
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
     
mongo-replicaset:
  priorityClassName: thingpark-enterprise-data
  replicaSet:
    resources:
      limits:
        memory: 850Mi
  arbiter:
    resources:
      limits:
        memory: 200Mi

zookeeper:
  priorityClassName: thingpark-enterprise-data
  resources:
    limits:
      memory: 128Mi
    requests:
      memory: 128Mi

mariadb-galera:
  priorityClassName: thingpark-enterprise-data
  resources:
    limits:
      memory: 400Mi


sql-proxy:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 150Mi

lrc:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  lrc:
    resources:
      limits:
        memory: 250Mi
  lrcSync:
    resources:
      limits:
        memory: 100Mi
  sftp:
    resources:
      limits:
        memory: 20Mi
  rfscanBatch:
    resources:
      limits:
        memory: 20Mi

lrc-proxy:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 50Mi

support:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 30Mi

wireless-pki:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 880Mi

locsolver:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 20Mi

tp-gui:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 50Mi

smp-tpe:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 60Mi

twa:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 800Mi

twa-admin:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 100Mi

twa-dev:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 600Mi

twa-ran:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 600Mi

twa-task-res:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 300Mi

twa-alarm-notif:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi

task-notif-ws:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 300Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 10

tpx-flow:
  priorityClassName: thingpark-enterprise-data-path
  engine:
    replicaCount: 2
    resources:
      limits:
        memory: 256Mi
  supervisor: 
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  hub:
    replicaCount: 2
    resources:
      limits:
        memory: 300Mi
  bridge: 
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  api:
    replicaCount: 2
    resources:
      limits:
        memory: 300Mi

tp-dx:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 300Mi

node-red:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi

nssa:
  priorityClassName: thingpark-enterprise-services
  networkSurvey:
    replicaCount: 1
    resources:
      limits:
        memory: 20Mi  
  spectrumAnalysis:
    replicaCount: 1
    resources:
      limits:
        memory: 20Mi

wlogger:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 150Mi

shellinabox:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 20Mi

# Configuration for controllers
ingress-nginx:
  controller:
    priorityClassName: thingpark-enterprise-data-path
    resources:
      limits:
        memory: 256Mi

