# Values configuring Thingpark Enterprise deployment for Azure Kubernetes Service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  storageType: "az-premium-lrs"
## Node selector for Thingpark Enterprise deployment on only 3 nodes
nodeSelectorKey: &nodeSelectorKey "thingpark.enterprise.actility.com/nodegroup-name"
nodeSelectorValue: &nodeSelectorValue "tpe"
nodeSelector: &nodeSelector
  thingpark.enterprise.actility.com/nodegroup-name: *nodeSelectorValue
tolerations: &tolerations
  - key: *nodeSelectorKey
    operator: "Equal"
    value: *nodeSelectorValue
    effect: "NoSchedule"
## thingpark-data-controllers
psmdb-operator:
  tolerations: *tolerations
  nodeSelector: *nodeSelector
strimzi-kafka-operator:
  tolerations: *tolerations
  nodeSelector: *nodeSelector
## thingpark-enterprise-controllers
cert-manager:
  nodeSelector: *nodeSelector
  tolerations: *tolerations
  webhook:
    nodeSelector: *nodeSelector
    tolerations: *tolerations
  cainjector:
    nodeSelector: *nodeSelector
    tolerations: *tolerations
## thingpark-enterprise
acmeSolvers:
  - http01:
      ingress:
        class: nginx-tpe
        podTemplate:
          spec:
            nodeSelector: *nodeSelector
            tolerations: *tolerations

sql-proxy:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
## Persistent Volume Claim setting to use EBS volumes for persistence
lrc:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  lrc:
    resources:
      limits:
        memory: 1024Mi
  lrcSync:
    resources:
      limits:
        memory: 100Mi
  sftp:
    resources:
      limits:
        memory: 100Mi
  rfscanBatch:
    resources:
      limits:
        memory: 100Mi
  njsProxy:
    resources:
      limits:
        memory: 100Mi
  persistence:
    storageClass: "thingpark-premium-lrs-ext4"
    ftpStorageClass: "thingpark-premium-lrs-xfs"
  nodeSelector: *nodeSelector
  tolerations: *tolerations
lrc-proxy:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 2
  resources:
    limits:
      memory: 200Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
support:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
wireless-pki:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 1024Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
locsolver:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
tp-gui:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 50Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
smp-tpe:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 1024Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa-admin:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 128Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa-dev:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 768Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa-ran:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 768Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa-task-res:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 300Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
twa-alarm-notif:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 50Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
task-notif-ws:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 512Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 10
  nodeSelector: *nodeSelector
  tolerations: *tolerations
tpx-flow:
  priorityClassName: thingpark-enterprise-data-path
  engine:
    replicaCount: 2
    resources:
      limits:
        memory: 256Mi
  supervisor:
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  hub:
    replicaCount: 2
    resources:
      limits:
        memory: 250Mi
  bridge:
    replicaCount: 1
    resources:
      limits:
        memory: 300Mi
  api:
    replicaCount: 2
    resources:
      limits:
        memory: 250Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
tp-dx:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 400Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
node-red:
  priorityClassName: thingpark-enterprise-data-path
  replicaCount: 1
  resources:
    limits:
      memory: 200Mi
  persistence:
    storageClass: "thingpark-premium-lrs-xfs"
  nodeSelector: *nodeSelector
  tolerations: *tolerations
nssa:
  priorityClassName: thingpark-enterprise-services
  networkSurvey:
    replicaCount: 2
    resources:
      limits:
        memory: 100Mi
  spectrumAnalysis:
    replicaCount: 2
    resources:
      limits:
        memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
wlogger:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 2
  resources:
    limits:
      memory: 300Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
shellinabox:
  priorityClassName: thingpark-enterprise-services
  replicaCount: 1
  resources:
    limits:
      memory: 100Mi
  nodeSelector: *nodeSelector
  tolerations: *tolerations
# Configuration for controllers
ingress-nginx:
  controller:
    priorityClassName: thingpark-enterprise-data-path
    resources:
      limits:
        memory: 256Mi
    nodeSelector: *nodeSelector
    tolerations: *tolerations
    admissionWebhooks:
      patch:
        tolerations: *tolerations
## Data stack configuration
kafka-cluster:
  priorityClassName: thingpark-enterprise-data
  kafka:
    resources:
      limits:
        memory: 700Mi
    persistence:
      local: false
      storageClass: "thingpark-premium-lrs-xfs"
  zookeeper:
    resources:
      limits:
        memory: 384Mi
    persistence:
      local: false
      storageClass: "thingpark-premium-lrs-xfs"
  tolerations: *tolerations
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: *nodeSelectorKey
                operator: In
                values:
                  - *nodeSelectorValue
mongo-replicaset:
  priorityClassName: thingpark-enterprise-data
  resources:
    limits:
      memory: 3500Mi
  persistence:
    local: false
    storageClass: "thingpark-premium-lrs-xfs"
  replicaSet:
    nodeSelector: *nodeSelector
    tolerations: *tolerations
  arbiter:
    nodeSelector: *nodeSelector
    tolerations: *tolerations
zookeeper:
  priorityClassName: thingpark-enterprise-data
  resources:
    limits:
      memory: 512Mi
  persistence:
    storageClass: "thingpark-premium-lrs-xfs"
  nodeSelector: *nodeSelector
  tolerations: *tolerations
## thingpark-data
mariadb-galera:
  priorityClassName: thingpark-enterprise-data
  resources:
    limits:
      memory: 700Mi
  persistence:
    storageClass: "thingpark-premium-lrs-xfs"
  nodeSelector: *nodeSelector
  tolerations: *tolerations
