# Mandatory values & additional usual values to define for a Thingpark Enterprise helm release.
# Advanced settings detailed in chart values file
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ### INSTALLATION ID ###
  # Provided by Actility
  installationId: &installationId "" # MANDATORY
  ### FEATURE ACTIVATION ###
  # Defaults disable Node Red 
  # featuresActivation:
  #   dxApi: true
  #   iotFlow: true
  #   nodeRed: false
  ### MAIL SETTINGS ###
  # Default configuration not need any mail relay
  outgoingMail: {}
    ## SMTP enabled configuration sample
    # outgoingMail: 
    #   smtpServer: "smtp.example.com"
    #   smtpAuth:
    #     login: "user"
    #     password: "pass"
    #   port: "465"
    #   noReplyEmail: "noreply@example.com"
    #   smtpSecurity: ssl
  ### BASESTATION SECURITY ###
  # MANDATORY: TLS (X.509) for base station to TPE connection. Choose in IPSEC_X509, DISABLE or MIXED
  # Changing the security level to MIXED is authorized anytime. Changing the security level in any other cases might cause existing base stations to stop working.
  defaultBsSecurity: "IPSEC_X509" 
  ### AS SECURITY LEVEL ###
  # When set to 'strict' (recommanded), auto-signed certificates are rejected
  asSecurity: strict
  ### DNS HOSTNAME ###
  # MANDATORY: Defines the URL used to access the portal GUI
  dnsHostname: &dnsHostname "enterprise.actility.local" 

  ### MAP SERVICE ###
  # External Map service configuration
  mapService: {}
  # Google maps as map service
  # mapService:
  #   defaultLocation: "" 
  #   api: "gmaps"
  #   apiKey: ""
  ## Openstreet maps config sample
  # mapService: 
  #   defaultLocation: ""
  #   api: "osm"
  #   osmTile: ""
  #   osmNominatim: ""

  ### LORA CONFIGURATION ###
  # MANDATORY: configure Lora networking regarding you use case 
  # WARNING : This parameter must be set at initial configuration of TPE Platform. Changing it afterwards can generate malfunction between the devices and the base stations
  lora:
    # List of ISM band. Must not be changed once base stations and devices are deployed.
    ismBand: 
    - "eu868"
    # LoRaWAN; 24 bits network identifier.A dedicated NetID assigned by the LoRa Alliance.
    netId: "000001"

  ### THINGPARK REPOSITORY CONFIGURATION ###
  # No additional configuration required when use production repositories
  repositories:
    containerImagesRegistry:
      auth: 
        username: *installationId
        password: *installationId


  ### INBOUND: TLS CERTIFICATE ###
  ## OPTION 1: Default configuration, A Selfsigned certificate is generated
  ## OPTION 2: Using a externally generated certificate
  # ingress:
  #   tls:
  #     issuer: "external"
  #     certificate: |
  #       -----BEGIN CERTIFICATE-----
  #       -----END CERTIFICATE-----
  #     key: | 
  #       -----BEGIN PRIVATE KEY-----
  #       -----END PRIVATE KEY-----
  ## OPTION 3: Letsencrypt issued certificate. Uncomment acmeSolvers only if you want to use other challenge like dns
  # ingress:
  #   tls:
  #     issuer: "letsencrypt"
  #     acmeEmail: foo@example.com
  #     acmeSolvers:
  #     - http01:
  #         ingress:
  #           class: nginx-tpe

# For the OPTION 3 Letencrypt, netx block should be uncommented
# Require a public access to ingress and a resolved FQDN 
# tp-gui:
#   ingress:
#     rootIngress:
#       annotations:
#         cert-manager.io/cluster-issuer: "letsencrypt-prod"

### INBOUND: FLOW & DNS ###
# Configure ingress-nginx controller for DNS and Inbound base station flows
ingress-nginx:
# MANDATORY: configure ingress for inbound base stations:
# <namespace> MUST be replaced by your deployment namespace
  tcp:
    # Support ssh inbound
    2022: <namespace>/support-inbound:22
    # LRC tls inbounds
    3001: <namespace>/lrc-proxy:3001
    3101: <namespace>/lrc-proxy:3101
    # LRC sftp tls inbound
    3002: <namespace>/lrc-proxy:3002
    ## Additional Clear inbounds for base stations, uncomment to use "DISABLE" or "MIXED" as defaultBsSecurity
    # LRC clear inbounds
    # 2404: <namespace>/lrc-0:2404
    # 2504: <namespace>/lrc-1:2404
    # LRC sftp inbound
    # 3102: <namespace>/lrc-cluster:22
# OPTIONAL: DNS dynamic provisioning
## OPTION1: AZURE controller configuration to attach DNS to loadbalancer 
## dnsHostname should be composed of Azure DNS alias followed by Azure region domain name (i.e. thingpark-enterprise.westeurope.cloudapp.azure.com)
#  controller:
#    service:
#      annotations:
#        service.beta.kubernetes.io/azure-dns-label-name: thingpark-enterprise
## OPTION2: AMAZON Route 53 subdomain using external-dns controller
## Use a comma list to use optional dashboard : external-dns.alpha.kubernetes.io/hostname: enterprise.mycompany.org,dashboard.mycompany.org
#   controller:
#     service:
#       annotations:
#         external-dns.alpha.kubernetes.io/hostname: *dnsHostname

### BACKUP CONFIGURATION ###
# MANDATORY: A storage volume is required for upgrade rollback
backup: {}
# OPTION 1: Configuration to use a minio local deployment ( https://docs.min.io/)
# backup:
#   schedule: "30 2 * * *"
#   ttl: "720h0m0s"
#   s3Compat: 
#     url: http://minio.thingpark-enterprise-tools.svc:9000
#     accessKey: minio
#     secretKey: minio123
#     bucket: "thingpark-enterprise-backup"

# OPTION 2: Configuration to use AMAZON S3 bucket
# backup:
#   schedule: "30 2 * * *"
#   ttl: "720h0m0s"
#   amazon:
#     accessKey: 
#     secretAccessKey: 
#     region: us-east-2
#     bucket: "thingpark-enterprise-backup"

# OPTION 3: Configuration to use Azure blob storage
# backup:
#   schedule: "30 2 * * *"
#   ttl: "720h0m0s"
#   azure:
#     resourceGroup: <resource group>
#     storageAccount: <storage account>
#     blobContainer: thingpark-enterprise-backup
#     cloudName: AzurePublicCloud  # Available values: AzurePublicCloud AzureUSGovernmentCloud, AzureChinaCloud, AzureGermanCloud
#     subscriptionId: <>
#     tenantId: <>
#     clientId: <>
#     clientSecret: <>


### DATABASE PASSWORD OVERRINDING ###
  # sqlDb:
  #   accounts:
  #     admin:
  #       username: root
  #       password: ""
  #     twa:
  #       username: "twa"
  #       password: ""
  #     smp:
  #       username: "smp"
  #       password: ""
  #     ejbca:
  #       username: "ejbca"
  #       password: ""
  #     wlogger:
  #       username: "wlogger"
  #       password: ""
  #     tpdx:
  #       username: "tpdx"
  #       password: ""
  #     tpdxKeystore:
  #       username: tpdx_keystore
  #       password: ""
  #     tpdxDataflows:
  #       username: tpdx_dataflows
  #       password: ""
  #     tpxConnector:
  #       username: tpx_connector
  #       password: ""
  #     tpxFlowHub:
  #       username: tpx_flow_hub
  #       password: ""
  #     tpxFlowApi:
  #       username: tpx_flow_api 
  #       password: ""
  #     tpxFlowBridge:
  #       username: tpx_flow_bridge
  #       password: ""
  #     tpxFlowSupervisor:
  #       username: tpx_flow_supervisor
  #       password: ""

  # mongoDb:
  #   accounts:
  #     admin:
  #       username: clusterAdmin
  #       password: ""
  #     userAdmin:
  #       username: userAdmin
  #       password: ""
  #     userBackup:
  #       username: backup
  #       password: ""
  #     twa:
  #       username: twa
  #       password: ""
  #     smp:
  #       username: smplite
  #       password: ""
  #     rfscan:
  #       username: rfscan 
  #       password: ""
  #     netSurvey:
  #       username: "netsurvey"
  #       password: ""
  #     driver:
  #       username: "driver"
  #       password: ""
  #     keyInstaller:
  #       username: key-installer
  #       password: ""



