# Mandatory values & additional usual values to define for a Thingpark Enterprise helm release.
# Advanced settings detailed in chart values file
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullSecrets:
   - name: "thingpark-image-pull-secret"
  ### INSTALLATION ID ###
  # Provided by Actility
  installationId: "" # MANDATORY
  ### FEATURE ACTIVATION ###
  # Defaults disable Node Red 
  # featuresActivation:
  #   dxApi: true
  #   iotFlow: true
  ### MAIL SETTINGS ###
  # Default configuration not need any mail relay
  outgoingMail: {}
    ## SMTP enabled configuration sample
    # outgoingMail: 
    #   smtpServer: "smtp.example.com"
    #   smtpAuth:
    #     login: "user"
    #     password: "pass"
    #   port: "465"
    #   noReplyEmail: "noreply@example.com"
    #   smtpSecurity: ssl
    ## Maximum time in minutes before an action permit sent by a user (e.g. forgot password e-mail) is expired. 
    ## This value is recommended to be short because it is expected that the user would react to self-created action quickly.
    #   actionTokenGeneratedByUserLifespan: 15
    ## Maximum time in minutes before an action permit sent to a user by admin (e.g. account creation) is expired. 
    ## This value is recommended to be long to allow admins send e-mails for users that are currently offline
    #   actionTokenGeneratedByAdminLifespan: 60
  ### AS SECURITY LEVEL ###
  # When set to 'strict' (recommanded), auto-signed certificates are rejected
  asSecurity: strict
  ### DNS HOSTNAME ###
  # MANDATORY: Defines the URL used to access the portal GUI
  dnsHostname: &dnsHostname "enterprise.actility.local" 

  ### MAP SERVICE ###
  # External Map service configuration
  mapService: {}
  # Google maps as map service
  # mapService:
  #   defaultLocation: "" 
  #   api: "gmaps"
  #   apiKey: ""
  ## Openstreet maps config sample
  # mapService: 
  #   defaultLocation: ""
  #   api: "osm"
  #   osmTile: ""
  #   osmNominatim: ""

  ### LORA CONFIGURATION ###
  # MANDATORY: configure Lora networking regarding you use case 
  # WARNING : This parameter must be set at initial configuration of TPE Platform. Changing it afterwards can generate malfunction between the devices and the base stations
  lora:
    # List of ISM band. Must not be changed once base stations and devices are deployed.
    ismBand: 
    - "eu868"
    # LoRaWAN; 24 bits network identifier.A dedicated NetID assigned by the LoRa Alliance.
    netId: "000001"

  ### THINGPARK REPOSITORY CONFIGURATION ###
  # No additional configuration required when use production repositories
  # repositories:
  #   containerImagesRegistry:
  #     fqdn: "<private-registry>"

  ### FEDERATION CONFIGURATION ###
  ## 1. First installation procedure must be done before attempting to enable federation. First admininstrator must be created with the email of an existing user in the federated IDP
  ## 2. To enable authentication federation, a client must be registered with the identity provider that will authenticate users. This identity provider must be compatible with OpenID Connect 1.0.
  ## The client must have the following properties:
  ## - Redirection URI: https://<.Values.global.dnsHostname>/auth/federation-callback
  ## - Post logout redirect URI: https://<.Values.global.dnsHostname>/federation-post-logout
  ## - Response types: code
  ## - Token endpoint auth method: client_secret_basic
  ## - The openid, email and profile scopes must be allowed
  ## 3. Fill the oauthFederation block with identity provider settings and update helm release to push new configuration
  oauthFederation: {}
  # oauthFederation:
  #   issuer: ""
  #   clientId: ""
  #   clientSecret: ""

  ### SNMP CONFIGURATION ###
  ## Configure device & base station alarms notifications
  # snmp:
  #   trap:
  #     server: ""
  #     community: "public"

  ### MAXIMUM IOT FLOW CONNECTION ###
  ## Set the maximum number of IoT flow connections allowed simultaneously. 
  ## As each connection consumes hardware resources (CPU, RAM), this value should be set carefully
  # iotFlow:
  #   maxConnections: 5

  ### THINGPARK WIRELESS SETTINGS ###
  # wireless:
  #  ## LoRaWAN traffic lifespan (days)
  #  ## Set the lifespan of LoRaWAN uplink and downlink frames. 
  #  ## The default value of 15 days is enough for a normal usage of ThingPark Enterprise. 
  #  ## Extending the default value consumes hardware resources (RAM, Disk space), please contact your support before any change.
  #   deviceHistoryExpiration: 15
  
  ### LOGO CUSTOMIZATION ###
  ## Operator logo customization
  ## Uncomment and update following sample with your base64 encoded logo to replace the default one
  # logo: |-
  #   iVBORw0KGgoAAAANSUhEUgAAASwAAABkAQMAAAAGz5+DAAAABlBMVEUAAAD///+l2Z/dAAABxElE
  #   QVRIx+3WUWrDMAwAUIUOvI+BbzCzk+QsPUkSPJZrOctHj7GGXSCfGQRrkmy36doy/42BC6nl5tFU
  #   spUUMOc1Q2GFFVbYfTYW9udM4bg0iJbndGg6Bjk74dxIzGyGZnSaB+xbg0s14Qo1e2ickZiZg3ps
  #   FQ0Ge2BOX0Ix4hMYmRthLTHYEdP4BgqPsKdDEXuEZ5krYZWv3+sOD17ha0N8fUGHwvxTvZOYGX3i
  #   mgE/sMeW8rBYUeacT4UPNHJMzFNmDo9Slo7S6um9l1R3BAeJia2Gc56FWaqBopmmkS/T0cgxszqx
  #   T2F6w+wlG4VNdIHEQp0Dm5ktl8wbGs2GmR+srRLzACBsjDGzJrAFrtnhmh3zmMtk5xS8kX0UmAn7
  #   LTH7C4uZ9humN0xfMn0u7y22ntiwWYUTwzuMl15tmIrMJNbF39fdYnzxkEJgvC3thtnYgCoVRMor
  #   m3zArxPjOPYCs45OM+OW4U2fGMeps2Sx9sK4AXl9E+M49aksfagbt/NCDZkYx6nreetVgaGe0Es7
  #   B+ZjO8f0Y+llF9M+OL/cnefCmPf4yGQ2j6kcdlizGN/AspjJYXxzzUlhV/45FFbYv2TfBY6xkn7J
  #   B10AAAAASUVORK5CYII=

  ### INBOUND: TLS CERTIFICATE ###
  ## OPTION 1: Default configuration, A Selfsigned certificate is generated
  # ingress:
  #   ## Uncomment to override default behavior that configure global.dnsHostname as hosts for all ingress
  #   hosts: []
  #   ## BASICS STATION LNS: you have to update the LNS service port, uncomment next line
  #   lnsPublicPort: 4443
  #   baseStation:
  #     ## Hash of the password configured in the base stations to connect the key-installer service. 
  #     ## The hash must be provided in the SHA512 format, for example using the openssl passwd -6 command. 
  #     ## This password should be set only if base stations are flashed with custom images.
  #     keyInstallerPasswordHash: 
  #     ## Set an alternative fqdn to use for base stations endpoints. It configure both IEC over TLS and LNS endpoints. 
  #     fqdn:
  ## OPTION 2: Using a externally generated certificate
  ## Warning: global.ingress.tls.issuer.certificate must include server certificate first, and next the chain of trust
  # ingress:
  #   ## Uncomment to override default behavior that configure global.dnsHostname as hosts for all ingress
  #   hosts: []
  #   ## BASICS STATION LNS: you have to update the LNS service port, uncomment next line
  #   lnsPublicPort: 4443
  #   ## BASE STATION CONFIGURATION ## 
  #   baseStation:
  #     ## Hash of the password configured in the base stations to connect the key-installer service. 
  #     ## The hash must be provided in the SHA512 format, for example using the openssl passwd -6 command. 
  #     ## This password should be set only if base stations are flashed with custom images.
  #     keyInstallerPasswordHash: 
  #     ## Set an alternative fqdn to use for base stations endpoints. It configure both IEC over TLS and LNS endpoints.
  #     ## When Basics Station is used, the server certificate  below should use both global.dnsHostname and baseStation.fqdn as dnsNames (SAN)
  #     fqdn:
  #   tls:
  #     issuer: "external"
  #     ## Must include server certificate first, and next the chain of trust
  #     certificate: |
  #       -----BEGIN CERTIFICATE-----
  #       -----END CERTIFICATE-----
  #       -----BEGIN CERTIFICATE-----
  #       -----END CERTIFICATE-----
  #     key: | 
  #       -----BEGIN PRIVATE KEY-----
  #       -----END PRIVATE KEY-----
  #     ## Root certificate of authority that have issued server certiticate
  #     caCertificate: | 
  #       -----BEGIN PRIVATE KEY-----
  #       -----END PRIVATE KEY-----
  ## OPTION 3: Letsencrypt issued certificate. Uncomment acmeSolvers only if you want to use other challenge like dns
  # ingress:
  #   ## Uncomment to override default behavior that configure global.dnsHostname as hosts for all ingress
  #   hosts: []
  #   ## BASICS STATION LNS: you have to update the LNS service port, uncomment next line
  #   lnsPublicPort: 4443
  #   ## BASE STATION CONFIGURATION ## 
  #   baseStation:
  #     ## Hash of the password configured in the base stations to connect the key-installer service. 
  #     ## The hash must be provided in the SHA512 format, for example using the openssl passwd -6 command. 
  #     ## This password should be set only if base stations are flashed with custom images.
  #     keyInstallerPasswordHash: 
  #     ## Set an alternative fqdn to use for base stations endpoints. It configure both IEC over TLS and LNS endpoints. 
  #     fqdn:
  #   tls:
  #     issuer: "letsencrypt"
  #     acmeEmail: foo@example.com
  #     # acmeSolvers:
  #     # - http01:
  #     #     ingress:
  #     #       class: nginx-tpe
  #             podTemplate:
  #               spec:
  #                 imagePullSecrets:
  #                 - name: thingpark-image-pull-secret
  #     ## Root certificate of authority that have issued server certiticate
  #     caCertificate: | 
  #       -----BEGIN PRIVATE KEY-----
  #       -----END PRIVATE KEY-----

### BACKUP CONFIGURATION ###
## OPTIONAL: A storage volume is required for manual or automated
## OPTION 1: Configuration to use a minio local deployment ( https://docs.min.io/)
#   backup:
#     schedule: "30 2 * * *"
#     s3Compat: 
#       url: http://minio.thingpark-enterprise-tools.svc:9000
#       accessKey: minio
#       secretAccessKey: minio123
#       bucket: "thingpark-enterprise-backup"

## OPTION 2: Configuration to use AMAZON S3 bucket
## accessKey and secretAccessKey are optional. If not provided, EKS Node Group IAM Role must allow get/put to S3 backup bucket
#   backup:
#     schedule: "30 2 * * *"
#     amazon:
#       accessKey: 
#       secretAccessKey: 
#       region: us-east-2
#       bucket: "thingpark-enterprise-backup"

## OPTION 3: Configuration to use Azure blob storage
#   backup:
#     schedule: "30 2 * * *"
#     azure:
#       resourceGroup: <resource group>
#       storageAccount: <storage account>
#       blobContainer: thingpark-enterprise-backup
#       cloudName: AzurePublicCloud  # Available values: AzurePublicCloud AzureUSGovernmentCloud, AzureChinaCloud, AzureGermanCloud
#       subscriptionId: <>
#       tenantId: <>
#       clientId: <>
#       clientSecret: <>

### DATABASE PASSWORD OVERRINDING ###
  # sqlDatabase:
  #   accounts:
  #     admin:
  #       username: root
  #       password: ""
  #     maintenance:
  #       username: maintenance
  #       password: "maintenance"
  #     twa:
  #       username: "twa"
  #       password: ""
  #     smp:
  #       username: "smp"
  #       password: ""
  #     ejbca:
  #       username: "ejbca"
  #       password: ""
  #     wlogger:
  #       username: "wlogger"
  #       password: ""
  #     tpdx:
  #       username: "tpdx"
  #       password: ""
  #     tpdxKeystore:
  #       username: tpdx_keystore
  #       password: ""
  #     tpdxDataflows:
  #       username: tpdx_dataflows
  #       password: ""
  #     tpxConnector:
  #       username: tpx_connector
  #       password: ""
  #     tpxFlowHub:
  #       username: tpx_flow_hub
  #       password: ""
  #     tpxFlowApi:
  #       username: tpx_flow_api 
  #       password: ""
  #     tpxFlowBridge:
  #       username: tpx_flow_bridge
  #       password: ""
  #     tpxFlowSupervisor:
  #       username: tpx_flow_supervisor
  #       password: ""

  # mongoDatabase:
  #   accounts:
  #     admin:
  #       username: clusterAdmin
  #       password: ""
  #     userAdmin:
  #       username: userAdmin
  #       password: ""
  #     userBackup:
  #       username: backup
  #       password: ""
  #     twa:
  #       username: twa
  #       password: ""
  #     smp:
  #       username: smplite
  #       password: ""
  #     rfscan:
  #       username: rfscan 
  #       password: ""
  #     netSurvey:
  #       username: "netsurvey"
  #       password: ""
  #     driver:
  #       username: "driver"
  #       password: ""
  #     keyInstaller:
  #       username: key-installer
  #       password: ""

# For the OPTION 1 Selfsigned certificate, next block should be uncommented
# Require a public access to ingress and a resolved FQDN 
# tp-gui:
#   ingress:
#     items:
#       gui:
#         annotations:
#           cert-manager.io/issuer: "internal-ca-issuer"

# For the OPTION 3 Letencrypt, next block should be uncommented
# Require a public access to ingress and a resolved FQDN 
# tp-gui:
#   ingress:
#     items:
#       gui:
#         annotations:
#           cert-manager.io/issuer: "letsencrypt-prod"

### INBOUND: FLOW & DNS ###
# Configure ingress-nginx controller for DNS and Inbound base station flows
ingress-nginx:
  imagePullSecrets: 
    - name: "thingpark-image-pull-secret"
# MANDATORY: configure ingress for inbound base stations:
# <namespace> MUST be replaced by your deployment namespace
  tcp:
    # Support ssh inbound
    2022: <namespace>/support-inbound:22
    # LRC tls inbounds
    3001: <namespace>/lrc-proxy:3001
    3101: <namespace>/lrc-proxy:3101
    # LRC sftp tls inbound
    3002: <namespace>/lrc-proxy:3002
    # Uncomment to expose Basics Station LNS endpoint
    # 4443: <namespace>/lrc-proxy-lns:8443
  # controller:
  #   image:
  #     registry: "<private-registry>"
  #   admissionWebhooks:
  #     patch:
  #       image:
  #         registry: "<private-registry>"
# OPTIONAL: DNS dynamic provisioning
## OPTION1: AZURE controller configuration to attach DNS to loadbalancer 
## dnsHostname should be composed of Azure DNS alias followed by Azure region domain name (i.e. thingpark-enterprise.westeurope.cloudapp.azure.com)
#  controller:
#    service:
#      annotations:
#        service.beta.kubernetes.io/azure-dns-label-name: thingpark-enterprise
## OPTION2: AMAZON Route 53 subdomain using external-dns controller
## Use a comma list to use optional dashboard : external-dns.alpha.kubernetes.io/hostname: enterprise.mycompany.org,dashboard.mycompany.org
#   controller:
#     service:
#       annotations:
#         external-dns.alpha.kubernetes.io/hostname: *dnsHostname


### ISOLATION CONFIGURATION ###
# Once your cluster use a networking plugin which supports NetworkPolicy, you can start to filter thingpark workloads ingress. 
# It allow to isolate workload running in the Thingpark deployment namespace from other. Only flow exposed by ingress controller are allowed
# Egress policies are currently not supported
# networkPolicy:
#   ingress:
#     enabled: true

# tpx-flow:
#   kafka:
#     topicConfigRetentionMs: 21600000 # connection topics retention duration between 6 hours (21600000 Ms) and 240 hours (864000000 Ms)

### PKI CONFIGURATION ###
# wireless-pki:
#   certProfiles:
#     ## Update the base station client certificate validity
#     lrrClient:
#       validity: 3y  # (*y *mo *d *h *m *s) - y=365 days, mo=30 days

# cert-manager:
#   image:
#     registry: "<private-registry>"
#   webhook:
#     image:
#       registry: "<private-registry>"
#   cainjector:
#     image:
#       registry: "<private-registry>"
#   acmesolver:
#     image:
#       registry: "<private-registry>"
#   startupapicheck:
#     image:
#       registry: "<private-registry>"
